apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  ingress: 
    className: nginx 
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-secret
      key: username
    passwordSecret:
      name: keycloak-secret
      key: password
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: keycloak.yourdomain.com
  proxy:
    headers: xforwarded
